FROM python:3.10-slim

WORKDIR /app

# copiar requirements primero para cache
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copiar TODO el proyecto, incluyendo templates
COPY . .

# asegurar permisos
RUN chmod -R 755 /app

CMD ["gunicorn", "manager:app", "--bind", "0.0.0.0:5000"]
